spring:

  #kafka基础配置,不要变动
  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: 1
      properties:
        linger.ms: 1000
        batch.size: 200000
        max.block.ms: 10000
        buffer.memory: 100554432
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      enable-auto-commit: false
      max-poll-records: 2
      properties:
        max.poll.interval.ms: 60000
        session.timeout.ms: 10000
        heartbeat.interval.ms: 3000
    properties:
      security:
        protocol: SASL_PLAINTEXT
      sasl:
        mechanism: PLAIN
      request.timeout.ms: 31000
    listener:
      ack-mode: MANUAL_IMMEDIATE
      concurrency: 1


    bootstrap-servers: 192.168.2.104:9092
    properties:
      sasl:
        jaas:
          config: org.apache.kafka.common.security.plain.PlainLoginModule required username="admin" password="admin";
  topics:
    topticTest:
      topic: topic001
      group: topic001
#logging:
#  level:
#    root: debug
